name: build-on-push
on: [push]
jobs:
  build_w32:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: CMake
      run: cmake -DBONZOMATIC_64BIT="NO" -DBONZOMATIC_WINDOWS_FLAVOR:STRING="GLFW" -G "Visual Studio 16 2019" -A Win32 .
    - name: Build
      run: cmake --build . --config Release
  build_w64:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: CMake
      run: cmake -DBONZOMATIC_64BIT="YES" -DBONZOMATIC_WINDOWS_FLAVOR:STRING="GLFW" -G "Visual Studio 16 2019" -A x64 .
    - name: Build
      run: cmake --build . --config Release
  build_linux:
    runs-on: ubuntu-latest
    steps:
    - name: Install deps
      run: sudo apt-get update && sudo apt-get install -q -y xorg-dev libasound2-dev libfontconfig1-dev libgl1-mesa-dev libglu1-mesa-dev
    - name: Checkout
      uses: actions/checkout@v1
    - name: Build
      run: cmake . && cmake --build .
  build_osx:
    runs-on: macOS-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Build
      run: cmake . && cmake --build .
